export default [
  {
    id: 1,
    name: 'Asia Pacific (Mumbai)',
    city: 'Mumbai',
    lat: 19.07609,
    lon: 72.877426,
    bucket: 'lellengeindia',
    region: 'ap-south-1',
    accelerated: true,
    endpoint: 'https://lellengeindia.s3-accelerate.amazonaws.com',
    edgeDomain: 'd2blaz750au7gw.cloudfront.net',
  },
  {
    id: 2,
    name: 'Asia Pacific (Seoul) ',
    city: 'Seoul',
    lat: 37.5326,
    lon: 127.024612,
    bucket: 'lellengeseoul',
    region: 'ap-northeast-2',
    accelerated: true,
    endpoint: 'https://lellengeseoul.s3-accelerate.amazonaws.com',
    edgeDomain: 'd5lwjuilx3xrr.cloudfront.net',
  },
  {
    id: 3,
    name: 'Asia Pacific (Singapore) ',
    city: 'Singapore',
    lat: 1.29027,
    lon: 103.851959,
    bucket: 'lellengesingapore',
    region: 'ap-southeast-1',
    accelerated: true,
    endpoint: 'https://lellengesingapore.s3-accelerate.amazonaws.com',
    edgeDomain: 'd3qnbgot7kk6nl.cloudfront.net',
  },
  {
    id: 4,
    name: 'Asia Pacific (Sydney) ',
    city: 'Sydney',
    lat: -33.865143,
    lon: 151.2099,
    bucket: 'lellengesydney',
    region: 'ap-southeast-2',
    accelerated: true,
    endpoint: 'https://lellengesydney.s3-accelerate.amazonaws.com',
    edgeDomain: 'd3pbptsyilcuuk.cloudfront.net',
  },
  {
    id: 5,
    name: 'Asia Pacific (Tokyo) ',
    city: 'Tokyo',
    lat: 35.652832,
    lon: 139.839478,
    bucket: 'lellengetokyo',
    region: 'ap-northeast-1',
    accelerated: true,
    endpoint: 'https://lellengetokyo.s3-accelerate.amazonaws.com',
    edgeDomain: 'd24aiel7ioa3zt.cloudfront.net',
  },
  {
    id: 6,
    name: 'Canada (Central)',
    city: 'Central',
    lat: 49.895077,
    lon: -97.138451,
    bucket: 'lellengecanada',
    region: 'ca-central-1',
    accelerated: true,
    endpoint: 'https://lellengecanada.s3-accelerate.amazonaws.com',
    edgeDomain: 'd2jfrm61sm1ei0.cloudfront.net',
  },
  {
    id: 8,
    name: 'EU (Frankfurt) ',
    city: 'Frankfurt',
    lat: 50.110924,
    lon: 8.682127,
    bucket: 'lellengefrankfurt',
    region: 'eu-central-1',
    accelerated: true,
    endpoint: 'https://lellengefrankfurt.s3-accelerate.amazonaws.com',
    edgeDomain: 'd2wxmcnqtzxdl6.cloudfront.net',
  },
  {
    id: 9,
    name: 'EU (Ireland) ',
    city: 'Ireland',
    lat: 53.35014,
    lon: -6.266155,
    bucket: 'lellengeireland',
    region: 'eu-west-1',
    accelerated: true,
    endpoint: 'https://lellengeireland.s3-accelerate.amazonaws.com',
    edgeDomain: 'd3bg5htbk31hn5.cloudfront.net',
  },
  {
    id: 11,
    name: 'EU (London) ',
    city: 'London',
    lat: 51.509865,
    lon: -0.118092,
    bucket: 'lellengelondon',
    region: 'eu-west-2',
    accelerated: true,
    endpoint: 'https://lellengelondon.s3-accelerate.amazonaws.com',
    edgeDomain: 'd10e48payh8ubh.cloudfront.net',
  },
  {
    id: 12,
    name: 'EU (Paris) ',
    city: 'Paris',
    lat: 48.864716,
    lon: 2.349014,
    bucket: 'lellengeparis',
    region: 'eu-west-3',
    accelerated: true,
    endpoint: 'https://lellengeparis.s3-accelerate.amazonaws.com',
    edgeDomain: 'd2e3sav8apk7dk.cloudfront.net',
  },
  {
    id: 14,
    name: 'EU (Stockholm) ',
    city: 'Stockholm',
    lat: 59.334591,
    lon: 18.06324,
    bucket: 'lellengestockholm',
    region: 'eu-north-1',
    accelerated: false,
    endpoint: 'https://lellengestockholm.s3.eu-north-1.amazonaws.com',
    edgeDomain: 'd3v64ihf4jsp3b.cloudfront.net',
  },
  {
    id: 15,
    name: 'US East (N. Virginia) ',
    city: 'N. Virginia',
    lat: 37.54129,
    lon: -77.434769,
    bucket: 'lellengenvirginia',
    region: 'us-east-1',
    accelerated: true,
    endpoint: 'https://lellengenvirginia.s3-accelerate.amazonaws.com',
    edgeDomain: 'd1d1r5di97tzvo.cloudfront.net',
  },
  {
    id: 16,
    name: 'US East (Ohio) ',
    city: 'Ohio',
    lat: 39.983334,
    lon: -82.98333,
    bucket: 'lellengeohio',
    region: 'us-east-2',
    accelerated: true,
    endpoint: 'https://lellengeohio.s3-accelerate.amazonaws.com',
    edgeDomain: 'd25dztwpdne7d5.cloudfront.net',
  },
  {
    id: 18,
    name: 'US West (N. California) ',
    city: 'N. California',
    lat: 37.733795,
    lon: -122.446747,
    bucket: 'lellengencalifornia',
    region: 'us-west-1',
    accelerated: true,
    endpoint: 'https://lellengencalifornia.s3-accelerate.amazonaws.com',
    edgeDomain: 'd3ih45sam07tw3.cloudfront.net',
  },
  {
    id: 19,
    name: 'US West (Oregon) ',
    city: 'Oregon',
    lat: 44.052071,
    lon: -123.086754,
    bucket: 'lellengeoregon',
    region: 'us-west-2',
    accelerated: true,
    endpoint: 'https://lellengeoregon.s3-accelerate.amazonaws.com',
    edgeDomain: 'd8biiywl6umyy.cloudfront.net',
  },
  {
    id: 20,
    name: 'South America (São Paulo) ',
    city: 'São Paulo',
    lat: -23.533773,
    lon: -46.62529,
    bucket: 'lellengesaupaulo',
    region: 'sa-east-1',
    accelerated: false,
    endpoint: 'https://lellengesaupaulo.s3-accelerate.amazonaws.com',
    edgeDomain: 'd3eb086r41nx6g.cloudfront.net',
  },
];
